### ISSUE TITLE
[Bug] Wrong parsing not required params

### ISSUE THREAD

**Issue by whalemare** [vilic/clime#56]
When I have 2 not-required params in my command, parsed only first one.

### Steps to reproduce:
1. Write command that have 2 not required params
```ts
@command()
export default class extends Command {
  execute(@param({required: false}) first: boolean, @param({required: false}) second: boolean) {
    console.log('first =', first)
    console.log('second =', second)
  }
}
```
2. Execute it and pass only `second`
`ts-node ./src/index.ts second`

### Expected
```
first = undefined
second = true
```

### But have
```
first = true
second = undefined
```

Sample:
https://github.com/lamantin-group/publish/blob/bug/clime/src/commands/default.ts#L20

**Comment by whalemare** [comment]
Some comments maybe? What I do wrong?

**Comment by vilic** [comment]
@whalemare I think the behavior is expected. You might want to use options instead of params in this case.

https://github.com/vilic/clime#parameter-types-and-options-schema

Thus use `command --first` or `command --second` or `command --first --second`

Another option is to use `@params() platforms` in the same example and do something like: `platforms.includes('ios')` or `platforms.includes('android')`

**Comment by whalemare** [comment]
Ok, thank you!
